image:
  file: .gitpod.Dockerfile


tasks:
  - name: "our db"
    command: |
     echo "first line"
     echo "second line"
     pwd
  - name: "start our db"
    command: /bin/bash /workspace/Dke_Winte/start_db.sh